"""Add label, task, task_label models

Revision ID: fd14238728a8
Revises: 7dc11e9fda02
Create Date: 2025-05-05 12:21:58.514804

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd14238728a8"
down_revision: Union[str, None] = "7dc11e9fda02"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "label",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("family_id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("color", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["family.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_label_family_id"), "label", ["family_id"], unique=False)
    op.create_table(
        "task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("family_id", sa.Integer(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("is_done", sa.Boolean(), nullable=False),
        sa.Column(
            "task_type", sa.Enum("SINGLE", "ROUTINE", name="tasktype"), nullable=False
        ),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("next_occurrence_date", sa.Date(), nullable=True),
        sa.Column("routine_settings", sa.JSON(), nullable=True),
        sa.Column("assignee_id", sa.Integer(), nullable=True),
        sa.Column("notes", sa.TEXT(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("parent_task_id", sa.Integer(), nullable=True),
        sa.Column("created_by_id", sa.Integer(), nullable=True),
        sa.Column("updated_by_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["family.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_task_id"],
            ["task.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_task_assignee_id"), "task", ["assignee_id"], unique=False)
    op.create_index(op.f("ix_task_family_id"), "task", ["family_id"], unique=False)
    op.create_index(
        op.f("ix_task_next_occurrence_date"),
        "task",
        ["next_occurrence_date"],
        unique=False,
    )
    op.create_table(
        "tasklabel",
        sa.Column("task_id", sa.Integer(), nullable=False),
        sa.Column("label_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["label_id"],
            ["label.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["task.id"],
        ),
        sa.PrimaryKeyConstraint("task_id", "label_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tasklabel")
    op.drop_index(op.f("ix_task_next_occurrence_date"), table_name="task")
    op.drop_index(op.f("ix_task_family_id"), table_name="task")
    op.drop_index(op.f("ix_task_assignee_id"), table_name="task")
    op.drop_table("task")
    op.drop_index(op.f("ix_label_family_id"), table_name="label")
    op.drop_table("label")
    # ### end Alembic commands ###
